version: '3'
services:
  storybook:
    container_name: ${PROJECT_SLUG}_storybook
    build:
      context: .
      dockerfile: storybook.Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env
    restart: always
    ports:
      - 6006:6006

  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    build:
      context: .
      dockerfile: ${ENVIRONMENT}.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - internal

networks:
  internal:
    name: ${PROJECT_SLUG}_internal
    driver: bridge
